FROM ubuntu:18.04

ENV MAGENTO_VERSION 2.1.17
ENV INSTALL_DIR /var/www/html
ENV COMPOSER_HOME /var/www/.composer/

#Add Bash and set bash as standard shell
RUN apt-get update
RUN apt-get install git -y